version: '3.8'
services:
  web:
    image: ci-cd-pipeline:prod
    container_name: ci-cd-pipeline-compose-prod
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
      labels:
        - "com.example.environment=production"
    environment:
      - FLASK_ENV=production