version: '3'
services:
  web:
    image: ci-cd-pipeline:prod
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: any
      labels:
        - "com.example.environment=production"
    environment:
      - FLASK_ENV=production
