name: Deploy to Production
on: push

env:
  # verbosity settting for Terraform logs
  TF_LOG: INFO
  # Credentials for deploying to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for Terraform state
  BUCKET_TF_STATE: ${{ secrets.PROD_BUCKET_TF_STATE }}
      


jobs:
  deploy-to-production: 
    if: github.repository != 'ella-adeka/CI-CD-Pipeline-Optimisation'
    # name: "Deploy to Production"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
        - name: Set up Terraform (prod)
          uses: hashicorp/setup-terraform@v1  # This step sets up Terraform

        - name: Initialise terraform for production
          run:  terraform init -reconfigure -backend-config="path=./terraform/environments/production/prod-backend.conf"

        - name: Validate Configuration
          run: terraform validate 

        - name: View resources to be created
          run: terraform plan

        - name: Terraform Apply (prod)
          run:  terraform apply -auto-approve