name: Deploy to Production
on:
  workflow_dispatch:
    branches:
      - main

env:
  # verbosity settting for Terraform logs
  TF_LOG: INFO
  # Credentials for deploying to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for Terraform state
  # BUCKET_TF_STATE: ${{ secrets.PROD_BUCKET_TF_STATE }}
      


jobs:
  deploy-to-production: 
    # if: github.repository != 'ella-adeka/CI-CD-Pipeline-Optimisation'
    # name: "Deploy to Production"
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read
    defaults:
      run:
        working-directory: terraform/environments/production
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform (prod)
        uses: hashicorp/setup-terraform@v2  # This step sets up Terraform
        with:
          terraform_version: 1.3.0
      - name: fix terraform file permissions
        run: find /tmp -name "terraform" -type f -exec chmod 755 {} +
      - name: Initialise terraform for production
        run:  terraform init -reconfigure -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY" -backend-config="region=eu-west-2"

      - name: Validate Configuration
        run: terraform validate 

      - name: View resources to be created
        run: terraform plan

      - name: Terraform Apply (prod)
        run:  terraform apply -auto-approve