# checkout jenkins

name: Test and Deploy Staging
on:
  workflow_dispatch:
    branches:
      - main

env:
#     # verbosity settting for Terraform logs
    TF_LOG: INFO
#     # Credentials for deploying to AWS
#     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     # S3 bucket for Terraform state
#     # BUCKET_TF_STATE: ${{ secrets.STATE_BUCKET_TF_STATE }}
        

jobs:
  test-staging: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./my_app/requirements.txt
          playwright install
          playwright install-deps
      - name: Test with pytest
        run: pytest ./tests/e2e/test_example.py
    
  deploy-to-staging: 
    # name: "Deploy to Staging"
    runs-on: ubuntu-latest
    # permissions:
    #   deployments: write
    #   contents: write
    #   statuses: write
    #   actions: write
    #   checks: read
    defaults:
      run:
        shell: bash
        working-directory: terraform/environments/staging
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform (staging)
        uses: hashicorp/setup-terraform@v3  # This step sets up Terraform
        with:
          terraform_version: 1.3.0
      - name: fix terraform file permissions
        run: find /tmp -name "terraform" -type f -exec chmod 755 {} +
      
      - name: echo
        run: echo "hellow"

      - name: Terraform Init (staging)
        id: init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  terraform init -backend-config="access_key=${{env.AWS_ACCESS_KEY_ID}}" -backend-config="secret_key=${{ env.AWS_SECRET_ACCESS_KEY}}" -backend-config="region=eu-west-2"
        # run:  terraform init -reconfigure -backend-config="access_key=${{env.AWS_ACCESS_KEY_ID}}" -backend-config="secret_key=${{env.AWS_SECRET_ACCESS_KEY}}" -backend-config="region=eu-west-2"
      
      # - name: Import bucket
      #   run: terraform import 'aws_s3_bucket.stag-backend-bucket' cicdpo-stag-tf-state-bucket

      - name: Validate Configuration
        run: terraform validate 

      - name: View resources to be created
        run: terraform plan

      - name: Terraform Action (staging)
        run:  terraform apply -auto-approve -input=false
