# checkout jenkins

name: Test and Deploy Staging
on: push

env:
    # verbosity settting for Terraform logs
    TF_LOG: INFO
    # Credentials for deploying to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # S3 bucket for Terraform state
    BUCKET_TF_STATE: ${{ secrets.STATE_BUCKET_TF_STATE }}
        

jobs:
  test-staging: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./my_app/requirements.txt
          playwright install
          playwright install-deps
      - name: Test with pytest
        run: pytest ./tests/e2e/test_example.py
    
  deploy-to-staging: 
    # name: "Deploy to Staging"
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Terraform (staging)
        uses: hashicorp/setup-terraform@v2  # This step sets up Terraform
        with:
          terraform_version: 1.3.0
      - name: Terraform Init (staging)
        run:  terraform init -reconfigure -backend-config="path=./terraform/environments/staging/stag-backend.conf"

      - name: Validate Configuration
        run: terraform validate 

      - name: View resources to be created
        run: terraform plan

      - name: Terraform Action (staging)
        run:  terraform apply -auto-approve -input=false
